version: '3'
services:

  database:
    image: postgres:13
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-database
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
    volumes:
      - ~/.volumes/database/postgresql:/var/lib/postgresql/data
    networks:
      - spring-boot-example-network
    tty: true

  api:
    build: 
      context: ../api
      dockerfile: ../api/docker/Dockerfile.prod
    image: throyer/springboot/spring-boot-example-network:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-api
    links:
      - database
    ports:
      - 8080:80
    environment:

      # database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SHOW_SQL: ${DB_SHOW_SQL}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}

      # security
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION_IN_HOURS: ${TOKEN_EXPIRATION_IN_HOURS}
      REFRESH_TOKEN_EXPIRATION_IN_DAYS: ${REFRESH_TOKEN_EXPIRATION_IN_DAYS}
      MINUTES_TO_EXPIRE_RECOVERY_CODE: ${MINUTES_TO_EXPIRE_RECOVERY_CODE}
      MAX_REQUESTS_PER_MINUTE: ${MAX_REQUESTS_PER_MINUTE}

      # smtp
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      # swagger
      SWAGGER_URL: ${SWAGGER_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
    networks:
      - spring-boot-example-network
    tty: true
    entrypoint: [
      "dockerize",
      "-wait",
      "tcp://database:${DB_PORT}",
      "-timeout",
      "20s",
      "java",
      "-jar",
      "api.jar"
    ]

  web:
    image: throyer/springboot/example-web:latest
    build: 
      context: ../web
      dockerfile: ../web/docker/Dockerfile.prod
      args:
        - APP_API_BASE_URL=${APP_API_BASE_URL}
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-web
    ports:
      - "8082:80"
    networks:
      - spring-boot-example-network
    tty: true

networks:
  spring-boot-example-network:
    driver: bridge